grpc.client.file-storage-service.address=static://localhost:9091
grpc.client.file-storage-service.enableKeepAlive=true
grpc.client.file-storage-service.negotiationType=plaintext
grpc.server.enabled=true
grpc.server.port=9090
server.port=9010
spring.application.name=metadata
spring.datasource.password=$DatA_BasE26
spring.datasource.url=jdbc:postgresql://localhost:5432/Rakumo
spring.datasource.username=postgres
spring.grpc.server.factory=netty
spring.grpc.server.servlet.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.main.allow-bean-definition-overriding=true
